include:
  - board: nice_nano_v2
    shield: kbdkid3_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: kbdkid3_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
