include:
  - board: nice_nano@2.0.0
    shield: kbdkid3_left nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: kbdkid3_right nice_view_adapter nice_view
  - board: seeeduino_xiao_ble
    shield: kbdkid3_dongle
  - board: nice_nano@2.0.0
    shield: settings_reset
