file_format: "1"
id: kbdkid3
name: kbdkid3
type: shield
url: https://github.com/Tubbles/kbdkid3
requires: [pro_micro]
features:
  - keys
siblings:
  - kbdkid3_left
  - kbdkid3_right
  - kbdkid3_dongle
